/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilQueryRouteImport } from './routes/perfil.$query'
import { Route as JogoSteamidAppidRouteImport } from './routes/jogo.$steamid.$appid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilQueryRoute = PerfilQueryRouteImport.update({
  id: '/perfil/$query',
  path: '/perfil/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoSteamidAppidRoute = JogoSteamidAppidRouteImport.update({
  id: '/jogo/$steamid/$appid',
  path: '/jogo/$steamid/$appid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfil/$query': typeof PerfilQueryRoute
  '/jogo/$steamid/$appid': typeof JogoSteamidAppidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfil/$query': typeof PerfilQueryRoute
  '/jogo/$steamid/$appid': typeof JogoSteamidAppidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfil/$query': typeof PerfilQueryRoute
  '/jogo/$steamid/$appid': typeof JogoSteamidAppidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfil/$query' | '/jogo/$steamid/$appid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfil/$query' | '/jogo/$steamid/$appid'
  id: '__root__' | '/' | '/perfil/$query' | '/jogo/$steamid/$appid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfilQueryRoute: typeof PerfilQueryRoute
  JogoSteamidAppidRoute: typeof JogoSteamidAppidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$query': {
      id: '/perfil/$query'
      path: '/perfil/$query'
      fullPath: '/perfil/$query'
      preLoaderRoute: typeof PerfilQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/$steamid/$appid': {
      id: '/jogo/$steamid/$appid'
      path: '/jogo/$steamid/$appid'
      fullPath: '/jogo/$steamid/$appid'
      preLoaderRoute: typeof JogoSteamidAppidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerfilQueryRoute: PerfilQueryRoute,
  JogoSteamidAppidRoute: JogoSteamidAppidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
